on:
  push:
    tags:
      - '*.*.*'
name: Build and Release
jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm i
          npm i -g @vscode/vsce

      - name: Build extension
        run: |
          mkdir -p builds
          npm run vsce:build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: false
          files: builds/own-dark-001-*.*.*.vsix

      - name: Clean up
        run: rm -rf ./builds
